-- TNBO Insights Service - MySQL reference schema (starter)

CREATE TABLE analytics_sessions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(100) NOT NULL UNIQUE,
    user_id VARCHAR(100) NULL,
    anonymous_id VARCHAR(100) NULL,
    device_id VARCHAR(150) NULL,
    platform VARCHAR(30) NULL,
    app_version VARCHAR(30) NULL,
    country_code VARCHAR(10) NULL,
    city VARCHAR(100) NULL,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    INDEX idx_sessions_user_id (user_id),
    INDEX idx_sessions_anonymous_id (anonymous_id),
    INDEX idx_sessions_started_at (started_at)
);

CREATE TABLE analytics_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    event_uuid CHAR(36) NOT NULL UNIQUE,
    session_id VARCHAR(100) NULL,
    user_id VARCHAR(100) NULL,
    anonymous_id VARCHAR(100) NULL,
    device_id VARCHAR(150) NULL,
    platform VARCHAR(30) NULL,
    app_version VARCHAR(30) NULL,
    event_name VARCHAR(100) NOT NULL,
    event_category VARCHAR(60) NULL,
    service VARCHAR(60) NOT NULL,
    surface VARCHAR(100) NULL,
    screen_name VARCHAR(100) NULL,
    block_id VARCHAR(100) NULL,
    block_type VARCHAR(60) NULL,
    placement_id BIGINT UNSIGNED NULL,
    position_index INT NULL,
    content_id VARCHAR(100) NULL,
    content_type VARCHAR(60) NULL,
    match_id VARCHAR(100) NULL,
    competition_id VARCHAR(100) NULL,
    team_id VARCHAR(100) NULL,
    sponsor_id BIGINT UNSIGNED NULL,
    campaign_id BIGINT UNSIGNED NULL,
    creative_id BIGINT UNSIGNED NULL,
    occurred_at TIMESTAMP NOT NULL,
    event_date DATE NOT NULL,
    properties JSON NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    INDEX idx_events_occurred_at (occurred_at),
    INDEX idx_events_event_date (event_date),
    INDEX idx_events_event_name (event_name),
    INDEX idx_events_service (service),
    INDEX idx_events_surface (surface),
    INDEX idx_events_user_id (user_id),
    INDEX idx_events_session_id (session_id),
    INDEX idx_events_campaign_id (campaign_id),
    INDEX idx_events_placement_id (placement_id),
    INDEX idx_events_content_id (content_id),
    INDEX idx_events_service_date (service, event_date),
    INDEX idx_events_service_surface_date (service, surface, event_date)
);
